module.exports = {
    brandname: "GALAXY VIRUS STORE",
    server_url: 'http://localhost:3000',
    database_host: 'localhost',
    database_port: 3307,
    database_user: "sa",
    database_password: "123456",
    database_database: "ProjectWebsite",
    email_email: "your_email",
    email_password: "your_password",
    contact_email: "your_email",
    contact_mobile: "your_mobile",
    card_username: "your_username",
    card_apikey: "your_apikey",
    bank_bankid: "your_bankid",
    bank_accountno: "your_accountno",
    bank_template: "your_template",
    bank_accountname: "your_accountname",
};