module.exports = {
    brandname: "your_trademark",
    server_url: 'your_website_url',
    database_host: 'your_database_host',
    database_port: 3306,
    database_user: "your_database_user",
    database_password: "your_database_password",
    database_database: "your_database_name",
    email_email: "your_email",
    email_password: "your_password",
    contact_email: "your_email",
    contact_mobile: "your_mobile",
    card_username: "your_username",
    card_apikey: "your_apikey",
    bank_bankid: "your_bankid",
    bank_accountno: "your_accountno",
    bank_template: "your_template",
    bank_accountname: "your_accountname",
};